const EVENT_TYPES = {
  USER_CREATED: "USER_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
};

const RPC_TYPES = {
  TEST_RPC: "TEST_RPC",
  GET_APPLICANT_DETAILS: "GET_APPLICANT_DETAILS",
  GET_APPLICANT_RESUMES: "GET_APPLICANT_RESUMES",
  GET_RESUME_SCORE: "GET_RESUME_SCORE",
  GET_RECRUITER_INTERVIEW_AVAILABLE: "GET_RECRUITER_INTERVIEW_AVAILABLE",
  DECREMENT_RECRUITER_INTERVIEW_AVAILABLE: "DECREMENT_RECRUITER_INTERVIEW_AVAILABLE",
  GET_RECRUITER_DETAILS: "GET_RECRUITER_DETAILS",
  TALENTPOOL_GET_ALL_STUDENT_USERS: "TALENTPOOL_GET_ALL_STUDENT_USERS",
  TALENTPOOL_GET_ALL_TALENTPOOL_USERS: "TALENTPOOL_GET_ALL_TALENTPOOL_USERS"
};

module.exports = {
  EVENT_TYPES,
  RPC_TYPES,
};
