const EVENT_TYPES = {
  USER_CREATED: "USER_CREATED",
  USER_LOGGED_IN: "USER_LOGGED_IN",
};

const RPC_TYPES = {
  TEST_RPC: "TEST_RPC",
  GET_APPLICANT_DETAILS: "GET_APPLICANT_DETAILS",
};

module.exports = {
  EVENT_TYPES,
  RPC_TYPES,
};
